# ============================
# MPPI Configuration File
# ============================

# MPPI Parameters
# These control the behavior of the Model Predictive Path Integral optimization.
dt: 0.01          # Time step size for simulation (in seconds).
n_samples: 50     # Number of trajectory samples per iteration.
lambda: 0.5       # Temperature parameter for trajectory cost weighting.
horizon: 40       # Prediction horizon (number of time steps).
n_workers: 1      # Number of parallel workers for optimization.
seed: 42          # Random seed for reproducibility.
beta: 0.5

# ============================
# Model Parameters for Contact Dynamics
# ============================
o_solref:
  - 0.02          # Time constant for contact model (stiffness control).
  - 1.0           # Damping ratio for the contact model.

# ============================
# Mujoco sensor data size
# ============================
sensor_data_size: 12

# ============================
# Spline Parameters
# ============================
sample_type: "cubic" # Spline interpolation type ("cubic" for cubic splines).
n_knots: 4          # Number of control points (knots) in the spline.

# ============================
# Noise Parameters
# ============================
# Noise standard deviations applied to control inputs for exploration.
noise_sigma:
  - 0.2 # Upper joint (finger 0)
  - 0.1  # Middle joint (finger 0)
  - 0.1  # Lower joint (finger 0)
  - 0.2 # Upper joint (finger 120)
  - 0.1  # Middle joint (finger 120)
  - 0.1  # Lower joint (finger 120)
  - 0.2 # Upper joint (finger 240)
  - 0.1  # Middle joint (finger 240)
  - 0.1  # Lower joint (finger 240)


# ============================
# Cost Function Parameters
# ============================

# Diagonal entries of the state cost matrix Q
# Higher values penalize deviations from reference states more heavily.
Q_diag:
  - 10 # Upper joint (finger 0)
  - 10 # Middle joint (finger 0)
  - 10 # Lower joint (finger 0)
  - 10 # Upper joint (finger 120)
  - 10 # Middle joint (finger 120)
  - 10 # Lower joint (finger 120)
  - 10 # Upper joint (finger 240)
  - 10 # Middle joint (finger 240)
  - 10 # Lower joint (finger 240)
  - 10 # Upper joint (finger 0)
  - 10 # Middle joint (finger 0)
  - 10 # Lower joint (finger 0)
  - 10 # Upper joint (finger 120)
  - 10 # Middle joint (finger 120)
  - 10 # Lower joint (finger 120)
  - 10 # Upper joint (finger 240)
  - 10 # Middle joint (finger 240)
  - 10 # Lower joint (finger 240)

# Diagonal entries of an individual cost term for frame position (This need to correspesond to the order in Mujoco's sensor_data)
W_frame_pos:
 - 100 # x-position (finger 0 tip frame)
 - 100 # y-position (finger 0 tip frame)
 - 100 # z-position (finger 0 tip frame)
 - 100 # x-position (finger 120 tip frame)
 - 100 # y-position (finger 120 tip frame)
 - 100 # z-position (finger 120 tip frame)
 - 100 # x-position (finger 240 tip frame)
 - 100 # y-position (finger 240 tip frame)
 - 100 # z-position (finger 240 tip frame)


W_cube_state:
  - 10000 # x-position
  - 10000 # y-position
  - 25000 # z-position
  - 0000 # w-quaternion
  - 0 # x-quaternion
  - 0 # y-quaternion
  - 0 # z-quaternion


# Diagonal entries of the control cost matrix R
# Penalizes excessive control effort (torque commands).
# R_diag:
#   - 0.0001 # Upper joint (finger 0)
#   - 0.0001  # Middle joint (finger 0)
#   - 0.0001  # Lower joint (finger 0)
#   - 0.0001 # Upper joint (finger 120)
#   - 0.0001  # Middle joint (finger 120)
#   - 0.0001  # Lower joint (finger 120)
#   - 0.0001 # Upper joint (finger 240)
#   - 0.0001  # Middle joint (finger 240)
#   - 0.0001  # Lower joint (finger 240)

R_diag:
  - 0 
  - 0 
  - 0 
  - 0 
  - 0 
  - 0 
  - 0 
  - 0 
  - 0 